<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <Company>HMD Software</Company>
    <Authors>LouiDev</Authors>
    <Product>Bastion Vault</Product>
    <Copyright>Copyright (c) 2026 LouiDev</Copyright>
    <Version>1.0.1</Version>
    <NeutralLanguage>en</NeutralLanguage>
    <PackageLicenseExpression>PolyForm-Noncommercial-1.0.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/LouiDev/BastionVault</RepositoryUrl>
    <PackageProjectUrl>https://github.com/LouiDev/BastionVault</PackageProjectUrl>
  </PropertyGroup>
</Project>
