<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <Company>HMD Software</Company>
    <Product>Bastion</Product>
    <Version>1.0.0</Version>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
</Project>
